ДЗ 10.1 Добавлены исключения
MihalGennadi4/qa-automation-java pull request #11
Opened 2022-05-22 19:55 UTC by MihalGennadi4

Добавлены исключения и пример для наглядности.
Также, при необходимости, метод isArgsValid можно использовать и для проверки на потерю наличия параметров у передаваемого message. 
Это не по ТЗ, а так, творчество на всякий случай.

2022-05-24 11:08 UTC, IgorSklyar approved these changes

2022-05-31 14:30 UTC, IgorSklyar requested changes
Супер! Задание выполнено, есть небольшие замечания

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/domain/Message.java
> +    public UUID getId() {return id;}
добавь плиз перенос после {

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/domain/Message.java
> +    public void setId(UUID id) {this.id = id;}
здесь тоже

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/domain/Message.java
> +    public void setId(UUID id) {this.id = id;}
здесь тоже

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/domain/Message.java
> +        this.id = null; //Хде защщита от NPE?? Стрелем себе по коленочкам
почему здесь  id=null ?

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/domain/Message.java
> +        this.id = null; //Хде защщита от NPE?? Стрелем себе по коленочкам
почему здесь  id=null ?

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/Application.java
> +        //service.log(service, message1, message2, message3, message4, message5, message6);
удали плиз коммент

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/Application.java
> +        //service.log(service, message1, message2, message3, message4, message5, message6);
удали плиз коммент

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/Application.java
> +        service.log(service, DESC, DISTINCT, repository.collectionToArray(repository.findBySeverity(MAJOR))); //вывод по уровню собщений
старайся избегать  комментариев в коде

2022-05-31 14:30 UTC, IgorSklyar commented on src/main/java/com/tcs/edu/Application.java
> +        service.log(service, DESC, DISTINCT, repository.collectionToArray(repository.findBySeverity(MAJOR))); //вывод по уровню собщений
старайся избегать  комментариев в коде

2022-05-31 14:33 UTC, MihalGennadi4 commented on src/main/java/com/tcs/edu/Application.java
> +        service.log(service, DESC, DISTINCT, repository.collectionToArray(repository.findBySeverity(MAJOR))); //вывод по уровню собщений
Ага, это писал чтоб ревьювить было легче))

2022-05-31 14:40 UTC, merged